# Generated by Django 6.0.2 on 2026-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_audio',
            field=models.FileField(blank=True, null=True, upload_to='profile_audio/'),
        ),
    ]
