# Generated by Django 6.0.3 on 2026-03-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_post_type_polloption_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_audio',
            field=models.FileField(blank=True, null=True, upload_to='profile_audio/'),
        ),
    ]
