# Generated by Django 6.0.3 on 2026-03-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_profile_audio'),
        ('core', '0004_alter_post_post_type_polloption_pollvote'),
    ]

    operations = [
    ]
